apiVersion: v1
kind: Service
metadata:
  name: {{ include "kouma.fullname" . }}-engine
  labels:
    {{- include "kouma.engine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.engine.service.type }}
  ports:
    - port: {{ .Values.engine.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kouma.engine.selectorLabels" . | nindent 4 }}
