{{- if not (and (not .Values.mongodb.enabled) .Values.externalMongodb.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kouma.fullname" . }}-secret
  labels:
    {{- include "kouma.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.mongodb.enabled }}
  KOUMA_DB_USERNAME: {{ .Values.mongodb.auth.username | quote }}
  KOUMA_DB_PASSWORD: {{ .Values.mongodb.auth.password | quote }}
  {{- else }}
  KOUMA_DB_USERNAME: {{ .Values.externalMongodb.username | quote }}
  KOUMA_DB_PASSWORD: {{ .Values.externalMongodb.password | quote }}
  {{- end }}
  KOUMA_DB_URI: {{ include "kouma.mongodb.uri" . | quote }}
{{- end }}
