apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kouma.fullname" . }}-engine
  labels:
    {{- include "kouma.engine.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.engine.replicaCount }}
  selector:
    matchLabels:
      {{- include "kouma.engine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/shared-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/shared-secret.yaml") . | sha256sum }}
        {{- with .Values.engine.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "kouma.engine.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.engine.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: engine
          image: {{ include "kouma.engine.image" . | quote }}
          imagePullPolicy: {{ .Values.engine.image.pullPolicy }}
          {{- with .Values.engine.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3002
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "kouma.configmapName" . }}
            {{- if and (not .Values.mongodb.enabled) .Values.externalMongodb.existingSecret }}
            - secretRef:
                name: {{ .Values.externalMongodb.existingSecret }}
            {{- else }}
            - secretRef:
                name: {{ include "kouma.fullname" . }}-secret
            {{- end }}
          env:
            {{- with .Values.common.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.engine.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: exchange-volume
              mountPath: /exchange
          {{- with .Values.engine.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: exchange-volume
          {{- if .Values.exchange.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "kouma.exchangePvcName" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.engine.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.engine.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.engine.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
