{{- if .Values.exchange.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kouma.exchangePvcName" . }}
  labels:
    {{- include "kouma.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.exchange.persistence.accessMode }}
  {{- if .Values.exchange.persistence.storageClass }}
  storageClassName: {{ .Values.exchange.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.exchange.persistence.size }}
{{- end }}
