{{- if .Values.nginx.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kouma.fullname" . }}-nginx
  labels:
    {{- include "kouma.nginx.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kouma.nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/nginx-config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "kouma.nginx.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: exchange-volume
              mountPath: /exchange
          {{- with .Values.nginx.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "kouma.fullname" . }}-nginx-config
        - name: exchange-volume
          {{- if .Values.exchange.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "kouma.exchangePvcName" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
