apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kouma.configmapName" . }}
  labels:
    {{- include "kouma.labels" . | nindent 4 }}
data:
  KOUMA_ENV: "docker"
  {{- $dbHost := include "kouma.mongodb.host" . }}
  {{- if $dbHost }}
  KOUMA_DB_HOST: {{ $dbHost | quote }}
  {{- end }}
  KOUMA_DB_PORT: {{ include "kouma.mongodb.port" . | quote }}
  KOUMA_DB_NAME: {{ include "kouma.mongodb.database" . | quote }}
  KOUMA_FS_HOST_URL: {{ include "kouma.fsHostUrl" . | quote }}
  KOUMA_EXCHANGE_ROOT_DIR: "/exchange"
  {{- if .Values.common.apiKeySecret }}
  KOUMA_API_KEY_SECRET: {{ .Values.common.apiKeySecret | quote }}
  {{- end }}
